<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" target-language="es" datatype="htmlbody" original="https://pypi.org/project/django-saml2-auth-idperror-redirect/">
    <body>
      <group id="django-saml2-auth-idperror-redirect">
        <trans-unit id="d92d8aca0ade6d85abbc01932fb7d8a39392119e" translate="yes" xml:space="preserve">
          <source>A plugin to redirect users to a URL (usually the login page) in response to an authentication error in
&lt;code&gt;django-saml2-auth&lt;/code&gt;.</source>
          <target state="translated">Un complemento para redirigir a los usuarios a una URL (generalmente la p&amp;aacute;gina de inicio de sesi&amp;oacute;n) en respuesta a un error de autenticaci&amp;oacute;n en &lt;code&gt;django-saml2-auth&lt;/code&gt; .</target>
        </trans-unit>
        <trans-unit id="c010015d9fb9b4768de87603e7a161cf6d3c27cb" translate="yes" xml:space="preserve">
          <source>By default, &lt;code&gt;django-saml2-auth&lt;/code&gt; redirects users to the &lt;code&gt;:denied&lt;/code&gt; page in response to authentication errors.
&lt;code&gt;django-saml2-auth-idperror-redirect&lt;/code&gt; will instead redirect the user to another URL (or view), usually the
login page.</source>
          <target state="translated">De forma predeterminada, &lt;code&gt;django-saml2-auth&lt;/code&gt; redirige a los usuarios a la p&amp;aacute;gina &lt;code&gt;:denied&lt;/code&gt; en respuesta a errores de autenticaci&amp;oacute;n. &lt;code&gt;django-saml2-auth-idperror-redirect&lt;/code&gt; redirigir&amp;aacute; al usuario a otra URL (o vista), generalmente la p&amp;aacute;gina de inicio de sesi&amp;oacute;n.</target>
        </trans-unit>
        <trans-unit id="a7fa515b0cd14cb34294ae3c8604ec88d81ec378" translate="yes" xml:space="preserve">
          <source>Django SAML2 Plugin for URL redirection on IDP Error (usually to an IdP login)</source>
          <target state="translated">Django SAML2 Plugin para la redirección de URL en el error de IDP (normalmente a un inicio de sesión de IdP)</target>
        </trans-unit>
        <trans-unit id="0f01ed56a1e32a05e5ef96e4d779f34784af9a96" translate="yes" xml:space="preserve">
          <source>Example</source>
          <target state="translated">Ejemplo</target>
        </trans-unit>
        <trans-unit id="f490c652308b651df8132649cabbd2ef9f41475f" translate="yes" xml:space="preserve">
          <source>In settings.py:</source>
          <target state="translated">En settings.py:</target>
        </trans-unit>
        <trans-unit id="2473e96bc614a911821242119918a241a41836d6" translate="yes" xml:space="preserve">
          <source>Introduction</source>
          <target state="translated">Introducción</target>
        </trans-unit>
        <trans-unit id="23558b05f791d2f94e61cc425bbb1c24a9ca4d61" translate="yes" xml:space="preserve">
          <source>django-saml2-auth-idperror-redirect</source>
          <target state="translated">django-saml2-auth-idperror-redirect</target>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
